version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
clone_folder: C:\Dev
clone_script:
- ps: >-
    git clone -q --recursive https://github.com/MaxKruse/Cpp-Osu-Music-Player.git

    cd Cpp-Osu-Music-Player

    git checkout -qf

    git submodule update --init --recursive
environment:
  APPVEYOR_RDP_PASSWORD: AppOsu!Music1
install:
- ps: >-
    Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-windows.zip' 'premake.zip'

    7z x premake.zip

    ./premake5 vs2017
build_script:
- ps: >-
    msbuild

on_failure:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
