#pragma once
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <Windows.h>
#include <string>
#include <vector>
#include <iostream>
#include <cstdio>
#include <sstream>
#include <fstream>
#include <map>
#include <algorithm>
#include <ctime>
#include <filesystem>