#pragma once
#include <stdio.h>
#include <math.h>
#include <Windows.h>
#include <string>
#include <vector>
#include <iostream>
#include <cstdio>
#include <sstream>
#include <fstream>
#include <map>
#include <algorithm>
#include <time.h>